name: Update Lambda Function

on:
  push:
    branches:
      - AAA_CI-CD_Lambda_function # Change this to your main branch name

jobs:
  deploy_source:
    name: Deploy lambda function from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: Deploy datahub lambda function
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: AAALambda_POC
          s3_bucket: demo-sagar-iceberg/
          s3_key: AAA_lambda_files/lambda_function.zip