name: Update Lambda Function

on:
  push:
    branches:
      - AAA_CI-CD_Lambda_function # Change this to your main branch name

jobs:
  deploy_source:
    name: Deploy lambda function from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9

      - name: Update Lambda Function Code
        run: |
          aws lambda update-function-code \
            --function-name AAALambda_POC \
            --s3-bucket demo-sagar-iceberg \
            --s3-key /AAA_lambda_files/lambda_function.py \
            --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

